// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZLTWIOTYlm7QNZLHVKt7768XbkgAlSOI',
    appId: '1:863058492073:web:f683715ca75681de5987b8',
    messagingSenderId: '863058492073',
    projectId: 'slearning-app',
    authDomain: 'slearning-app.firebaseapp.com',
    storageBucket: 'slearning-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC5hc6Pw7bmFBzVtGwA2eizQGJdk75dW8',
    appId: '1:863058492073:android:cff1063e8954f15a5987b8',
    messagingSenderId: '863058492073',
    projectId: 'slearning-app',
    storageBucket: 'slearning-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAANbmBbkI0eyWDhviayWueMqMYP7W_U8s',
    appId: '1:863058492073:ios:e41a712a1301b98d5987b8',
    messagingSenderId: '863058492073',
    projectId: 'slearning-app',
    storageBucket: 'slearning-app.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAANbmBbkI0eyWDhviayWueMqMYP7W_U8s',
    appId: '1:863058492073:ios:e41a712a1301b98d5987b8',
    messagingSenderId: '863058492073',
    projectId: 'slearning-app',
    storageBucket: 'slearning-app.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZLTWIOTYlm7QNZLHVKt7768XbkgAlSOI',
    appId: '1:863058492073:web:1f92776bcd835adb5987b8',
    messagingSenderId: '863058492073',
    projectId: 'slearning-app',
    authDomain: 'slearning-app.firebaseapp.com',
    storageBucket: 'slearning-app.firebasestorage.app',
  );
}
